[package]
name = "mysh"
version = "0.1.0"
authors = ["alexis <alexis.auriac@epitech.eu>"]
edition = "2018"

[dependencies]
isatty = "0.1"
nix = "0.14.0"
regex = "1"
lazy_static = "1.3.0"
ctrlc = "3.1.3"
